
package com.roytuts.jaxws.soapclient;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloServiceImpl", targetNamespace = "http://soapservice.jaxws.roytuts.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloServiceImpl {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://soapservice.jaxws.roytuts.com/", className = "com.roytuts.jaxws.soapclient.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://soapservice.jaxws.roytuts.com/", className = "com.roytuts.jaxws.soapclient.SayHelloResponse")
    @Action(input = "http://soapservice.jaxws.roytuts.com/HelloServiceImpl/sayHelloRequest", output = "http://soapservice.jaxws.roytuts.com/HelloServiceImpl/sayHelloResponse")
    public String sayHello();

}
