package com.jeejava.soap.contract.first;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-07-15T17:43:03.893+05:30
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "UserService",
                  wsdlLocation = "file:/C:/workspace/soap-contract-first-webservice/src/main/resources/wsdl/user.wsdl",
                  targetNamespace = "https://www.jeejava.com/UserService")
public class UserService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("https://www.jeejava.com/UserService", "UserService");
    public final static QName UserService = new QName("https://www.jeejava.com/UserService", "UserService");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/workspace/soap-contract-first-webservice/src/main/resources/wsdl/user.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/workspace/soap-contract-first-webservice/src/main/resources/wsdl/user.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public UserService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UserService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UserService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns UserPort
     */
    @WebEndpoint(name = "UserService")
    public UserPort getUserService() {
        return super.getPort(UserService, UserPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserPort
     */
    @WebEndpoint(name = "UserService")
    public UserPort getUserService(WebServiceFeature... features) {
        return super.getPort(UserService, UserPort.class, features);
    }

}
