package com.jeejava.soap.contract.first;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-07-15T17:43:03.781+05:30
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "https://www.jeejava.com/UserService", name = "UserPort")
@XmlSeeAlso({ObjectFactory.class})
public interface UserPort {

    @WebMethod
    @RequestWrapper(localName = "getUserDetailsRequest", targetNamespace = "https://www.jeejava.com/UserService", className = "com.jeejava.soap.contract.first.GetUserDetailsRequest")
    @ResponseWrapper(localName = "getUserDetailsResponse", targetNamespace = "https://www.jeejava.com/UserService", className = "com.jeejava.soap.contract.first.GetUserDetailsResponse")
    @WebResult(name = "user", targetNamespace = "https://www.jeejava.com/UserService")
    public com.jeejava.soap.contract.first.User getUserDetailsRequest(

        @WebParam(name = "id", targetNamespace = "https://www.jeejava.com/UserService")
        int id
    );
}
