package https.www_jeejava_com.userservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2019-07-12T21:21:45.054+05:30
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "https://www.jeejava.com/UserService", name = "UserPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UserPort {

    @WebMethod
    @WebResult(name = "getUserDetailsResponse", targetNamespace = "https://www.jeejava.com/UserService", partName = "getUserDetailsResponse")
    public GetUserDetailsResponse getUserDetails(
        @WebParam(partName = "getUserDetailsRequest", name = "getUserDetailsRequest", targetNamespace = "https://www.jeejava.com/UserService")
        GetUserDetailsRequest getUserDetailsRequest
    );
}
