package https.www_roytuts_com.userservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2019-07-12T21:21:45.271+05:30
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "UserPortService", 
                  wsdlLocation = "file:/C:/workspace/spring-boot-soap-consumer/src/main/resources/wsdl/users.wsdl",
                  targetNamespace = "https://www.roytuts.com/UserService") 
public class UserPortService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("https://www.roytuts.com/UserService", "UserPortService");
    public final static QName UserPortSoap11 = new QName("https://www.roytuts.com/UserService", "UserPortSoap11");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/workspace/spring-boot-soap-consumer/src/main/resources/wsdl/users.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserPortService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/workspace/spring-boot-soap-consumer/src/main/resources/wsdl/users.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserPortService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserPortService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public UserPortService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UserPortService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UserPortService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns UserPort
     */
    @WebEndpoint(name = "UserPortSoap11")
    public UserPort getUserPortSoap11() {
        return super.getPort(UserPortSoap11, UserPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserPort
     */
    @WebEndpoint(name = "UserPortSoap11")
    public UserPort getUserPortSoap11(WebServiceFeature... features) {
        return super.getPort(UserPortSoap11, UserPort.class, features);
    }

}
